### ISSUE TITLE
Provide bread crumbs to articles

### ISSUE THREAD

**Issue by tomkerkhove** [ZoinerTejada/azure-data-guide#15]
Provide bread crumbs to articles so that you can see what this section is about.

**Example:**
https://github.com/ZoinerTejada/azure-data-guide/blob/master/data-guide/common-architectures/transactional-data.md

**Proposal:**
*Common Architectures > Relational > Transactional Data*

**Remarks:**
This is probably done via the Azure documentation header but wanted to make sure that it's there as this can be interesting to see where you are.

**Comment by MikeWasson** [comment]
Yep. the publishing system for docs.microsoft.com automatically generates the breadcrumbs

**Comment by tomkerkhove** [comment]
Perfect, thanks!
