### ISSUE TITLE
ELT schematic in Data Pipelines has wrong headers

### ISSUE THREAD

**Issue by tomkerkhove** [ZoinerTejada/azure-data-guide#16]
The image in Extract, Transform & Load (ETL) has the wrong headers in the schematic and should be swapped:

![ELT schematic in Data Pipelines has wrong headers](https://user-images.githubusercontent.com/4345663/33525240-fd8e07d4-d82b-11e7-9caf-df8fb7810d40.png)

**Comment by joelhulen** [comment]
This appears to have happened when the designer converted all of the original images. I've fixed it. Thanks!

**Comment by tomkerkhove** [comment]
Thanks!
